# Generated by Django 6.0.6 on 2026-06-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Закрыта'), ('archived', 'Архив')], default='new', max_length=20)),
                ('lead_type', models.CharField(choices=[('callback', 'Заказать звонок'), ('team', 'Стать частью команды'), ('proposal', 'Запросить коммерческое предложение'), ('volunteer', 'Анкета добровольца'), ('review', 'Оставить отзыв'), ('study', 'Записаться на исследование'), ('question', 'Задать вопрос')], max_length=32)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('source_site', models.CharField(default='cliniss', max_length=80)),
                ('consent', models.BooleanField(default=False)),
                ('integration_key', models.CharField(blank=True, max_length=120)),
                ('external_payload', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
